resource_group_name  = "dev-tf-rg"
storage_account_name = "ansibletfstate"
container_name       = "devansiblestate"
key                  = "terraform.ansible.tfstate"
access_key           = "vjB7inOId5IJkfbXZRMW1lvZwCf0Teaq2NwAfwJB8gKYscB5+c7uJrnz/7wjolO7Gp0oJBcQ015lrMf4et3Nsw=="